# MLAppDeploy Project v0.1
project:
    name: test
    version: 0.0.1
    author: onetop21
workspace:
    ## Describe base docker image tag
    base: pytorch/pytorch:latest
    ## Describe package manager and dependency list to install pre-required.
    requires:
        pip: requirements.txt
    ## Describe environment variables.
    #env:  
    #    PYTHONUNBUFFERED: 1    
    ## Describe exclude files from project.
    #ignore:
    #   - "**/.*"
    ## Describe Pre/Post scripts for preparing.
    #prescripts: []
    #postscripts: []
    ## Describe application to execute
    #command: python run.py
    ## Describe arguments for execute application
    #arguments: --help
services:
    prepare:
        command: python prepare.py
    train:
        command: python train.py
        deploy:
            replicas: 1 
pipeline:
    - :prepare
    - prepare:train
    - train:analyze

    [
        (service, [previous_service, ...])
    ]
    - :capture
    - capture:detect
    - detect:recognize
    - detect,recognize:gaze

    #[SERVICENAME]:
    ## Describe image to run docker service for run not built image from workspace.
    #    image: 
    ## Describe environment variables additionaly.
    #    env:
    #        [KEY]: [VALUE]
    ## Describe services before running current service.
    #    depends: [ SERVICENAME, ... ]
    ## Describe command to need overwrite.
    #    command:
    ## Describe arguments to need overwrite.
    #    arguments:
    #
    ## Deploy only options
    #    deploy:
    ## Describe required system resource quote.
    #        quotes:
    #            cpus: 1
    #            mems: 8G
    #            gpus: 0
    ## Describe target node to run services.
    #        constraints:
    ## Describe number to run service instances.
    #        replicas: 1
    #...
